version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  main:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: circletest
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          # This assumes packages are installed via the install-package step above
          command: python manage.py test

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
