# Generated by Django 3.2.5 on 2021-08-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosestPointsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_points', models.TextField()),
                ('closest_pair', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
