# Generated by Django 3.2.5 on 2021-07-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosestPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_points', models.TextField()),
                ('closest_pair', models.CharField(max_length=255)),
            ],
        ),
    ]
