# Generated by Django 3.2.5 on 2021-07-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closestpoints',
            name='closest_pair',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
