# Generated by Django 3.2.5 on 2021-07-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_closestpoints_closest_pair'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClosestPoints',
            new_name='ClosestPointsData',
        ),
    ]
